
class MessageProcTypes(object):
    RELAY_MEMBERS = "RELAY_MEMBERS"
    UPDATE_MEMBER = "UPDATE_MEMBER"
    UPDATE_MEMBER_START = "UPDATE_MEMBER_START"
    NEXT_CANDIDATE = "NEXT_CANDIDATE"
    MEMBER = "MEMBER"
    SYNC = "SYNC"
